= README (Database Integration)
Thomas Phillips <tom@ridgebacknet.com>
:toc:
:toclevels: 2
:!numbered:

This repository contains training materials for integrating the Ridgeback Hunter database with other systems.
The materials are provided for free by Ridgeback Network Defense, Inc.
If you need assistance with the training materials or want help incorporating them into a course of your own, contact us at support@ridgebacknet.com.

== Ridgeback Hunter Database

Ridgeback Hunter maintains a local database in SQLite format.
The filename is:
```
/var/opt/ridgeback/ridgeback.db
```

You can access the database using the ```sqlite3``` command.

|===
| *Table* | *Description*
| failures | Record of any serious system or upgrade failures.
| history | For internal use. Database versions and install dates.
| log | Security information. This table contains data for reports and integration with other systems.
|===

To access the database, use the command:
```
sqlite3 /var/opt/ridgeback.db
```

Once connected to the database, use the SQLite command to inspect the table structure:
```
PRAGMA table_info(log);
```

== Queries

The following is a list of queries you may want to use for integrating Ridgeback Hunter with other systems.

|===
| *File* | *Description*
| link:src/sql/threat-hour-protocol.sql[threat-hour-protocol.sql] | Select and count all threats over the last 24 hours, grouped by hour, protocol.
| link:src/sql/threat-resolved-hour-protocol.sql[threat-resolved-hour-protocol.sql] | Select and count all threats resolved over the last 24 hours, grouped by hour, protocol.
| link:src/sql/mac_ip_joined.sql[mac_ip_joined.sql] | All MAC addresses and IP addresses that joined the network in the last 24 hours.
| link:src/sql/threat-day-hour-protocol.sql[threat-day-hour-protocol.sql] | Select and count all threats, grouped by day, hour, protocol.
| link:src/sql/hosts-contacting-decoys.sql[hosts-contacting-decoys.sql] | Select and count all hosts contacting decoys, over the last 24 hours.
|===

== About Ridgeback Hunter

Ridgeback Hunter is an interactive defense platform for network security and network management.
Ridgeback Hunter is extensible with commercial, custom, or open source plugins and widgets.
Let us know if you have requests for new features or extensions.

---

The website for Ridgeback Network Defense is:
http://www.ridgebacknet.com

Support is available at:
support@ridgebacknet.com
